source_directory: Example/Pods
xcodebuild_arguments: [-scheme,TokenDSDK]
exclude:
  - "Sources/TokenDSDK/Common/Utils/*"
  # - "Sources/TokenDSDK/Common/*"
  # - "Sources/TokenDSDK/API/*"
  # - "Sources/TokenDSDK/KeyServer/*"

readme: README.md
docset_icon: Resources/logo200.png

author: Distributed Lab
author_url: https://distributedlab.com
copyright: '© 2018 [Distributed Lab](https://distributedlab.com) under [open source license]().'

theme: fullwidth

disable_search:
  
skip_undocumented:

custom_categories:

  - name: API
    children:
      - API
      - BaseApi
      - BaseApiStack
      - BaseApiRequestBuilder
      - BaseApiRequestBuilderStack

  - name: Account
    children:
      - AccountApi
      - AccountRequestBuilder
      - Account
      - AccountRequest
      - Signers
      - SignersRequest

  - name: Asset pairs
    children:
      - AssetPairsApi
      - AssetPairsRequestBuilder
      - AssetPair
      - AssetPairsRequest

  - name: Assets
    children:
      - AssetsApi
      - AssetsRequestBuilder
      - Asset
      - AssetsRequest

  - name: Balances
    children:
      - BalancesApi
      - BalancesRequestBuilder
      - BalanceDetails
      - BalancesDetailsRequest

  - name: Charts
    children:
      - ChartsApi
      - ChartsRequestBuilder
      - ChartResponse
      - ChartsRequest
      - ChartsResponse

  - name: General
    children:
      - GeneralApi
      - GeneralRequestBuilder
      - FeeResponse
      - GetAccountIdRequest
      - GetFeeRequest
      - GetNetworkInfoRequest
      - NetworkInfoModel
      - NetworkInfoResponse
      - UserAccountIdResponse

  - name: Offers
    children:
      - OffersApi
      - OffersRequestBuilder
      - OfferResponse
      - OffersEmbedded
      - OffersOffersRequest
      - OffersOffersRequestParameters

  - name: Order book
    children:
      - OrderBookApi
      - OrderBookRequestBuilder
      - OrderBookEmbedded
      - OrderBookRequest
      - OrderBookResponse
      - OrderBookRequestParameters

  - name: Sales
    children:
      - SalesApi
      - SalesRequestBuilder
      - SaleResponse
      - SalesEmbedded
      - GetSaleDetailsRequest
      - GetSalesRequest
      - SaleDetailsResponse

  - name: Transactions
    children:
      - TransactionsApi
      - TransactionsRequestBuilder
      - CheckSaleStateOperationResponse
      - CheckSaleStateSubOperation
      - CreateIssuanceRequestResponse
      - CreateWithdrawalRequest
      - ManageOfferOperationResponse
      - ManageOfferSubOperation
      - OperationResponseBase
      - OperationResponseUnified
      - OperationsEmbedded
      - PaymentOperationResponse
      - PaymentV2OperationResponse
      - TransactionsPaymentsRequest
      - TransactionsPaymentsRequestParameters
      - TransactionsSendPaymentRequest

  - name: Users
    children:
      - UsersApi
      - UsersRequestBuilder
      - BlobResponse
      - CreateUserModel
      - CreateUserRequest
      - GetBlobRequest
      - GetUserRequest
      - GetUserResponse

  - name: Key Server
    children:
      - KeyServerApi
      - KeyServerApiRequestBuilder
      - CreateWalletRequest
      - EmailVerification
      - GetKDFParamsRequest
      - GetKDFParamsResponse
      - GetSignersRequest
      - GetWalletKDFRequest
      - GetWalletKDFResponse
      - GetWalletRequest
      - KDFParams
      - KeyPairBuilder
      - ResendEmailRequest
      - SystemInfo
      - SystemInfoRequest
      - UpdateWalletRequest
      - VerifyEmailRequest
      - WalletDataModel
      - WalletDataResponse
      - WalletDetailsModel
      - WalletInfoBuilder
      - WalletInfoModel
      - WalletInfoResponse
      - WalletKDFParams

  - name: Two-factor authentication
    children:
      - TFAApi
      - TFARequestBuilder
      - TFACodeMetaModel
      - TFACreateFactorModel
      - TFACreateFactorRequest
      - TFACreateFactorResponse
      - TFADeleteFactorRequest
      - TFAFactor
      - TFAFactorType
      - TFAGetFactorsRequest
      - TFAHandler
      - TFAHandlerProtocol
      - TFAMetaResponse
      - TFAPasswordHandler
      - TFAPasswordMetaModel
      - TFARequiredHandler
      - TFAResult
      - TFAUpdateFactorModel
      - TFAUpdateFactorRequest
      - TFAVerifyApi
      - TFAVerifyRequest
      - TFAVerifySignedTokenRequest
      - Array

  - name: API models
    children:
      - ApiCallbacks
      - ApiConfiguration
      - ApiDataRequest
      - ApiDataResponse
      - ApiError
      - ApiErrors
      - CancellableToken
      - HorizonError
      - RequestResultPage

  - name: Types
    children:
      - Empty
      - JSON

  - name: Formatters
    children:
      - AmountFormatterProtocol
      - AmountFormatters
      - DateFormatters
      - SunQueryAmountFormatter

  - name: Network
    children:
      - Network
      - RequestHeaders
      - RequestMethod
      - RequestParameters
      - RequestParametersEncoding
      - RequestSignKeyDataProviderProtocol
      - RequestSignParametersModel
      - RequestSigner
      - RequestSignerProtocol
      - UnsafeRequestSignKeyDataProvider
